### ISSUE TITLE
ERC228 support?

### ISSUE THREAD

**Issue by k06a** [Uniswap/contracts-vyper#1]
Are you going to add ERC228 interface support?
https://github.com/ethereum/EIPs/issues/228

**Comment by haydenadams** [comment]
@k06a  Not directly in the Vyper smart contracts. `change()` only represents 1 out of the 12 types of trades on Uniswap, so I would prefer to use the current function names.  It also uses uint16 which is supported in Solidity but not Vyper. 

I could pretty easily write an ERC228 Solidity contract that makes trades over Uniswap if its desired.
