### ISSUE TITLE
eth-typing version incompatibility

### ISSUE THREAD

**Issue by BlinkyStitt** [Uniswap/contracts-vyper#23]
While running `pip install -r requirements.txt` I noticed this warning:

```
py-evm 0.2.0a33 has requirement eth-typing<2.0.0,>=1.1.0, but you'll have eth-typing 2.0.0 which is incompatible.
```

Full logs: https://gist.github.com/WyseNynja/e448d5dc68a1c5a733919fa54f4a1a2e

**Comment by haydenadams** [comment]
should be fixed in v2 branch
