### ISSUE TITLE
contracts-vyper instruction

### ISSUE THREAD

**Issue by wkarshat** [Uniswap/contracts-vyper#28]
Using instruction for https://github.com/Uniswap/contracts-vyper

3.
install of requirements.txt uses cytoolz, which in turn needs  python3-dev

4.
cd vyper
    cd: vyper: No such file or directory

git reset --hard 35038d20bd9946a35261c4c4fbcb27fe61e65f78
    fatal: Could not parse object '35038d20bd9946a35261c4c4fbcb27fe61e65f78'.

**Comment by haydenadams** [comment]
Oops. I might have accidentally missed a step last time I updated the readme. 

3.5) 

```
pip uninstall vyper
git clone https://github.com/ethereum/vyper.git
```
