### ISSUE TITLE
End to End encryption of Uniswap to prevent front running

### ISSUE THREAD

**Issue by jwineman** [Uniswap/contracts-vyper#45]
Have you thought about implementing the PGP encryption architecture described here:

https://medium.com/fluidity/keyspace-end-to-end-encryption-using-ethereum-and-ipfs-87b04b18156b

This would prevent front running uniswap orders wouldn't it?

**Comment by evan-forbes** [comment]
one would need homomorphic encryption to compute contract logic privately, otherwise all encrypted messages would eventually have to be unencrypted to be computed. If the transactions are unencrypted before computation, then front running can always be a thing. 

https://link.medium.com/N6pFavtL32

**Comment by wjmelements** [comment]
front-running is a feature and not a bug. If you don't want to be front-run, use the minimum output parameter.

**Comment by jwineman** [comment]
Yeah I posted this when I was still pretty new to uniswap, I misunderstood what was going on under the hood.
